Feature 14 user story system monitoring tool documentation
ADORSYS-GIS/monitor-mind pull request #46
Opened 2023-11-10 10:14 UTC by Bansikah

Documentation on monitoring tools user story 14

2023-11-10 10:31 UTC, stephane-segning requested changes
Perfect! Just these 3 points...

2023-11-10 10:31 UTC, stephane-segning commented on services/__pycache__/time_service.cpython-310.pyc
Please remove this file, as it doesn't have a thing to do with your current ticket

2023-11-10 10:31 UTC, stephane-segning commented on services/__pycache__/memory_service.cpython-310.pyc
Please remove this file

2023-11-10 10:31 UTC, stephane-segning commented on services/__pycache__/cpu_service.cpython-310.pyc
Please remove this file

2023-11-10 11:14 UTC, Bansikah commented on services/__pycache__/memory_service.cpython-310.pyc
ok sir, right away

2023-11-11 07:37 UTC, stephane-segning approved these changes
Good!

2023-11-11 07:40 UTC, merged