Feature/30 implement test to validate network monitoring
ADORSYS-GIS/monitor-mind pull request #55
Opened 2023-11-10 11:43 UTC by kouamschekina

The script tests for network connection, system availability, does a port scan and network monitoring

2023-11-10 12:02 UTC, stephane-segning requested changes
The submitted code is good enough, but the target is missed. Please, try and copy the structure provided with the CPU example

2023-11-10 12:02 UTC, stephane-segning commented on app.py
> +def api_network(hostname):
Because it's an API Method (because of the `@app.route...`), this method should return something. Returning `print` is not a good thing.

2023-11-10 12:02 UTC, stephane-segning commented on app.py
> +    api_network(hostname)
You should never call explicitly an API Method

2023-11-10 12:57 UTC, kouamschekina commented on services/__pycache__/cpu_service.cpython-310.pyc
I have already solved it sir

2023-11-11 20:06 UTC, stephane-segning approved these changes
Good!

2023-11-11 20:15 UTC, merged